Settings:
  cron: 
  event_pattern: 
  target_event_bus_arn_after_execution: 
  iam_role_arn: 

# Settings:
#   cron: cron(15 10 * * ? *)
#   event_pattern: {
#     "source": ["aws.states"],
#     "detail-type": ["Step Functions Execution Status Change"],
#     "detail": {
#       "status": ["SUCCEEDED"],
#       "stateMachineArn": ["arn:aws:states:us-east-1:<AWS Account ID>:stateMachine:<StateMachine Name>"]
#     }
#   }
#   target_event_bus_arn_after_execution: arn:aws:events:ap-northeast-1:<AWS Account ID>:event-bus/default
#   iam_role_arn: arn:aws:iam::<AWS Account ID>:role/<IAM Role Name>