Settings:
  cron: 
  event_pattern: 
  target_event_bus_arn_after_execution: 
  xray_tracing: false
  iam_policy_document: 

# Example
#
# Settings:
#   cron: cron(15 10 * * ? *)
#   event_pattern: {
#     "source": ["aws.states"],
#     "detail-type": ["Step Functions Execution Status Change"],
#     "detail": {
#       "status": ["SUCCEEDED"],
#       "stateMachineArn": ["arn:aws:states:us-east-1:<AWS Account ID>:stateMachine:<StateMachine Name>"]
#     }
#   }
#   target_event_bus_arn_after_execution: arn:aws:events:ap-northeast-1:<AWS Account ID>:event-bus/default
#   xray_tracing: false
#   iam_policy_document: {
#       "Version": "2012-10-17",
#       "Statement": [
#           {
#               "Sid": "VisualEditor0",
#               "Effect": "Allow",
#               "Action": [
#                   "states:DescribeStateMachine",
#                   "states:DescribeExecution",
#                   "states:ListExecutions"
#               ],
#               "Resource": [
#                   "arn:aws:states:us-east-1:<AWS Account ID>:execution:*:*",
#                   "arn:aws:states:us-east-1:<AWS Account ID>:stateMachine:*"
#               ]
#           }
#       ]
#   }