# Example
#
# Settings:
#   deployment_destination_account_iam_role_arn: arn:aws:iam::<AWS Account ID>:role/SamDeployRoleStack-SamDeployRole-xxxx
#   event_bridge_rule:
#     - cron: cron(15 9 * * ? *)
#     - cron: cron(20 17 * * ? *)
#     - event_pattern: {
#         "source": ["aws.states"],
#         "detail-type": ["Step Functions Execution Status Change"],
#         "detail": {
#           "status": ["SUCCEEDED"],
#           "stateMachineArn": ["arn:aws:states:us-east-1:<AWS Account ID>:stateMachine:AAA"]
#         }
#       }
#       event_bus_arn: arn:aws:events:us-east-1:<AWS Account ID>:event-bus/default
#     - event_pattern: {
#         "source": ["aws.states"],
#         "detail-type": ["Step Functions Execution Status Change"],
#         "detail": {
#           "status": ["SUCCEEDED"],
#           "stateMachineArn": ["arn:aws:states:us-east-1:<AWS Account ID>:stateMachine:BBB"]
#         }
#       }
#       event_bus_arn: arn:aws:events:us-east-1:<AWS Account ID>:event-bus/default
#     - event_pattern: {
#         "source": ["aws.states"],
#         "detail-type": ["Step Functions Execution Status Change"],
#         "detail": {
#           "status": ["SUCCEEDED"],
#           "stateMachineArn": ["arn:aws:states:us-east-1:<AWS Account ID>:stateMachine:CCC"]
#         }
#       }
#       event_bus_arn: arn:aws:events:us-east-1:<AWS Account ID>:event-bus/default
#   target_event_bus_arn: 
#     - arn:aws:events:us-east-1:<AWS Account ID>:event-bus/StateMachineEventBus
#     - arn:aws:events:us-east-1:<AWS Account ID>:event-bus/default
#   xray_tracing: false
#   iam_policy_document: {
#       "Version": "2012-10-17",
#       "Statement": [
#           {
#               "Sid": "VisualEditor0",
#               "Effect": "Allow",
#               "Action": [
#                   "states:DescribeStateMachine",
#                   "states:DescribeExecution",
#                   "states:ListExecutions"
#               ],
#               "Resource": [
#                   "arn:aws:states:us-east-1:<AWS Account ID>:execution:*:*",
#                   "arn:aws:states:us-east-1:<AWS Account ID>:stateMachine:*"
#               ]
#           }
#       ]
#   }
#   tags:
#     - Key: System Name
#       Value: System 1
#     - Key: Environment
#       Value: production
  
Settings:
  deployment_destination_account_iam_role_arn: 
  event_bridge_rule:
    - cron: 
    - event_pattern: 
      event_bus_arn: 
  target_event_bus_arn: 
  xray_tracing: false
  iam_policy_document: 
  tags: